AllCops:
  Exclude:
    - 'lib/templates/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'spec/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'webpack/**/*'
    - 'public/**/*'
    - 'config/**/*'
    - 'Guardfile'
    - 'node_modules/**/*'

LineLength:
  Enabled: false
