language: ruby
rvm:
  - 2.3.0
services:
  - mysql
before_script:
  - sudo apt-get install -y phantomjs
  - mysql -e 'create database bn_test;'
  - foreman start &
script: CI=true RAILS_ENV=test bin/setup && bundle exec rake db:create db:migrate && bundle exec rspec spec/
