language: ruby
rvm:
  - 2.3.0
services:
  - mysql
before_script:
  - mysql -e 'create database bn_test;'
  - cp config/database.travis.yml config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate --trace
  - bundle exec rspec .
