language: ruby
env:
  - CI=true
  - RAILS_ENV=test
rvm:
  - 2.3.0
services:
  - mysql
before_script:
  - sudo apt-get install -y phantomjs
  - mysql -e 'create database bn_test;'
  - bin/setup
  - bundle exec rake db:create db:migrate
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install
script: bundle exec rspec spec/
