language: ruby
cache: bundler
rvm:
  - 2.3.0
services:
  - mysql
before_script:
  - sudo apt-get remove nodejs -y
  - sudo apt-get purge nodejs -y
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - npm install
  - sudo apt-get install -y phantomjs
  - mysql -e 'create database bn_test;'
  - RAILS_ENV=test bin/setup
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script: CI=true RAILS_ENV=test bundle exec rspec spec/
